### ISSUE TITLE
Crashes when sending emojis

### ISSUE THREAD

**Issue by matthe815** [matthe815/Starie-3.0#8]
The bot crashes on database entry due to the use of emojis. Error message below:

/var/Old File/Starie 3.0/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x92\x8E'' for column 'content' at row 1
    at Query.Sequence._packetToError (/var/Old File/Starie 3.0/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/var/Old File/Starie 3.0/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
    at Protocol._parsePacket (/var/Old File/Starie 3.0/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/var/Old File/Starie 3.0/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/var/Old File/Starie 3.0/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/Old File/Starie 3.0/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/var/Old File/Starie 3.0/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Connection.query (/var/Old File/Starie 3.0/node_modules/mysql/lib/Connection.js:208:25)
    at Client.client.on.e (/var/Old File/Starie 3.0/index.js:38:13)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at MessageCreateHandler.handle (/var/Old File/Starie 3.0/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/var/Old File/Starie 3.0/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/var/Old File/Starie 3.0/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (/var/Old File/Starie 3.0/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)
    at WebSocketClient.internalOnMessage (/var/Old File/node_modules/uws/uws.js:89:17)

**Comment by bennyman123abc** [comment]
Try parsing the emojis into a string or remove them from the message going into the database.
